"""GenomeFirewall synthetic evaluation scaffolding."""

from .attackers import (
    DEFAULT_SLICE_FIELDS,
    ScriptedAttackResult,
    run_adaptive_differencing_attack,
    run_subgroup_slicing_attack,
)
from .llm_attackers import (
    ClientBackedLLMPlanner,
    FakeLLMJSONClient,
    FeedbackMode,
    JSONProposalLLMPlanner,
    LLMClientConfig,
    LLMClientDryRunStatus,
    LLMJSONClient,
    LLMAttackResult,
    LLMProposalFunction,
    LLMQueryPlanner,
    OpenAICompatibleHTTPTransport,
    OpenAICompatibleLLMJSONClient,
    ReplayLLMPlanner,
    build_planner_view,
    dry_run_llm_client_config,
    load_llm_client_config_from_env,
    run_llm_adaptive_attack,
    workload_item_from_llm_payload,
)
from .query_log import QueryLogRecord
from .metrics import TranscriptSummary, summarize_transcript
from .policies import (
    AcceptedQueryRecord,
    MinimumCohortPolicy,
    NoPrivacyPolicy,
    PolicyDecision,
    PolicyEvaluation,
    StatefulPrivacyLedgerPolicy,
)
from .runner import QueryAttemptContext, evaluate_query_attempt, run_workload
from .synthetic import (
    GenomicQuery,
    SyntheticConfig,
    SyntheticDataset,
    evaluate_query,
    generate_synthetic_dataset,
    select_cohort,
)
from .workloads import (
    AttackTarget,
    WorkloadItem,
    generate_benign_operator_metadata_workload,
    generate_benign_workload,
    generate_benign_near_overlap_workload,
    generate_differencing_attack_workload,
    generate_subgroup_slicing_attack_workload,
    select_attack_target,
)

__all__ = [
    "GenomicQuery",
    "AcceptedQueryRecord",
    "ClientBackedLLMPlanner",
    "DEFAULT_SLICE_FIELDS",
    "FakeLLMJSONClient",
    "FeedbackMode",
    "JSONProposalLLMPlanner",
    "LLMClientConfig",
    "LLMClientDryRunStatus",
    "LLMJSONClient",
    "LLMAttackResult",
    "LLMProposalFunction",
    "LLMQueryPlanner",
    "MinimumCohortPolicy",
    "NoPrivacyPolicy",
    "OpenAICompatibleHTTPTransport",
    "OpenAICompatibleLLMJSONClient",
    "PolicyDecision",
    "PolicyEvaluation",
    "QueryAttemptContext",
    "QueryLogRecord",
    "ReplayLLMPlanner",
    "StatefulPrivacyLedgerPolicy",
    "SyntheticConfig",
    "SyntheticDataset",
    "TranscriptSummary",
    "ScriptedAttackResult",
    "AttackTarget",
    "WorkloadItem",
    "evaluate_query",
    "evaluate_query_attempt",
    "build_planner_view",
    "dry_run_llm_client_config",
    "generate_benign_operator_metadata_workload",
    "generate_benign_workload",
    "generate_benign_near_overlap_workload",
    "generate_differencing_attack_workload",
    "generate_subgroup_slicing_attack_workload",
    "generate_synthetic_dataset",
    "run_workload",
    "load_llm_client_config_from_env",
    "run_adaptive_differencing_attack",
    "run_llm_adaptive_attack",
    "run_subgroup_slicing_attack",
    "select_attack_target",
    "select_cohort",
    "summarize_transcript",
    "workload_item_from_llm_payload",
]
